### ISSUE TITLE
Automate deployment of updating rooms

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/ansible-scripts#10]
When updating the rooms frontend on a digital ocean droplet, each server will have unique requirements including:
- [x] will need to create a production build of `rooms-frontend` with custom environment variables pointing to the graphql server its using (local or external)
- [x] copy the production build over to `go-ssb-room/web/assets`
- [x] rebuild the docker container for the room

**Comment by cooldracula** [comment]
This issue is addressed in [planetary-social/ansible-scripts, PR#12](https://github.com/planetary-social/ansible-scripts/pull/12) and in [planetary-social/rooms-frontend, PR#103](https://github.com/planetary-social/rooms-frontend/pull/103).

I created a docker image with the production built dist/ folder being served from a simple nginx server.  With #12, we set up a host that runs on one domain, and so that means the rooms frontend can run separately, with its env pointing to `/graphql` instead of `someurl/graphql`.  

To update the frontend, you would just build the latest version, then build a new docker image and tag, and then run an ansible script with the new docker tag.  This is a part of the new ansible scripts (with some minor tweaking).
