### ISSUE TITLE
Automate deployment of graphql updates

### ISSUE THREAD

**Issue by chereseeriepa** [planetary-social/ansible-scripts#11]

**Comment by cooldracula** [comment]
This issue is addressed in [planetary-social/ansible-scripts, PR#12](https://github.com/planetary-social/ansible-scripts/pull/12)

**Comment by cooldracula** [comment]
@chereseeriepa , your advice on using pm2 helped a lot! The server seems to be more stable, but I think it might be because pm2 is handling the restarts and such.  @mixmix and I took a look at a running server and it seems like it's using a lot more memory than it should need.  We are going to pair later today on this and see if we can optimize its performance.

i think a combination of optimized code and pm2 will be the bee's knees on this!
